service:
  name: lambda-ops-metrics

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters


provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:DescribeAlarmHistory"
        - "cloudwatch:PutMetricData"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - events:PutRule
        - events:PutTargets
        - events:EnableRule
      Resource:
        - arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:rule/mtbf-ops-metrics-alarm-state-change
        - arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:rule/mttr-ops-metrics-alarm-state-change
        - arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:rule/mttf-ops-metrics-alarm-state-change


custom:
  topic: lambda-ops-metrics
  topicArn: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:lambda-ops-metrics


functions:
  mttr:
    handler: src/mttr.handler
    events:
      - cloudwatchEvent:
          name: mttr-ops-metrics-alarm-state-change
          description: ops health monitoring
          enabled: true
          event:
            source:
              - "aws.cloudwatch"
            detail-type:
              - "CloudWatch Alarm State Change"
  mttf:
    handler: src/mttf.handler
    events:
      - cloudwatchEvent:
          name: mttf-ops-metrics-alarm-state-change
          enabled: true
          event:
            source:
              - "aws.cloudwatch"
            detail-type:
              - "CloudWatch Alarm State Change"
  mtbf:
    handler: src/mtbf.handler
    events:
      - cloudwatchEvent:
          name: mtbf-ops-metrics-alarm-state-change
          enabled: true
          event:
            source:
              - "aws.cloudwatch"
            detail-type:
              - "CloudWatch Alarm State Change"
