service:
  name: lambda-ops-metrics

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters


provider:
  name: aws
  runtime: nodejs8.10
  # region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "cloudwatch:DescribeAlarmHistory"
        - "cloudwatch:PutMetricData"
      Resource: "*"


custom:
  topic: lambda-ops-metrics
  topicArn: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:lambda-ops-metrics


functions:
  mttr:
    handler: src/mttr.handler
    events:
      - sns:
          arn: ${self:custom.topicArn}
  mttf:
    handler: src/mttf.handler
    events:
      - sns:
          arn: ${self:custom.topicArn}
  mtbf:
    handler: src/mtbf.handler
    events:
      - sns:
          arn: ${self:custom.topicArn}


resources:
  Resources:
    MetricTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: ${self:custom.topic}